apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: demo-app:1.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: app-config-volume
              mountPath: /config/application.yaml
              subPath: application.yaml
      volumes:
        - name: app-config-volume
          secret:
            secretName: app-config
