apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-app.fullname" . }}{{ .Values.secret.nameSuffix }}
type: Opaque
data:
  application.yaml: {{ (.Files.Get "files/application.yaml") | b64enc }}
