apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "demo-app.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
{{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
