apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-app
  template:
    metadata:
      labels:
        app: currency-app
    spec:
      containers:
      - name: currency-app
        image: kishorek003/currency-app:latest   # <-- updated image
        imagePullPolicy: Always                  # <-- always pull latest from Docker Hub
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: currency-service
spec:
  type: LoadBalancer       # <-- changed from NodePort to LoadBalancer
  selector:
    app: currency-app
  ports:
    - protocol: TCP
      port: 80             # Public port
      targetPort: 5000     # Container port
