apiVersion: v1
kind: Service
metadata:
  name: simple-api-service
spec:
  selector:
    app: simple-api
  ports:
    - port: "{{ .Values.ports.serviceport }}"
      targetPort: "{{ .Values.ports.targetPort }}"
  type: NodePort
