apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.names.serviceaccountname }}"
  namespace: "{{ .Values.names.serviceaccountnamespace }}"
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::"{{ .Values.accountid }}":role/AWSLoadBalancerControllerRole
