apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-app
  template:
    metadata:
      labels:
        app: currency-app
    spec:
      containers:
      - name: currency-app
        image: currency-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: currency-service
spec:
  type: NodePort           # <-- Change this from ClusterIP
  selector:
    app: currency-app
  ports:
    - protocol: TCP
      port: 5000          # Internal cluster port
      targetPort: 5000    # Container port
      nodePort: 30007     # External port on localhost  
